name: Pipeline

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Grant permissions
      run: chmod +x gradlew; chmod +x *.sh

    - name: Compile, Code Analysis and Build
      run: ./gradlew build sonarqube
      
    - name: Packaging and Publishing
      uses: docker/build-push-action@v2.3.0
