# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Pipeline

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
  packaging:
#    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Build docker image
      uses: docker/build-push-action@v2.3.0
      with:
#        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
#        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
#        registry: docker.pkg.github.com
        tags: ${{ secrets.DOCKER_REGISTRY_URL }}/fvilarinho/demo
#        push: true

        
